---
# This file overrides settings from default.config.yml to match the Paddle
# server environment as good as possible for an optimal developer experience.
# Developer machine specific settings, such as path mappings, can be put in
# local.config.yml. See example.local.config.yml for an example local config
# YML file.
# See http://docs.drupalvm.com/en/latest/other/overriding-configurations/ for
# more information.
# Note: The merge of the variables in this file is shallow, so if you want to
# override a single item in a list, you will need to re-define all items in
# that list.
# Use a desktop version of Ubuntu so we get a graphical interface where we can
# see and interact with a browser while running a Selenium test.
#vagrant_box: boxcutter/ubuntu1604-desktop

# Don't use composer to build a local Paddle website.
build_composer_project: false

# Our Drupal code resides in the main synced directory, not in a 'drupal/web'
# sub folder.
drupal_core_path: "/var/www/tcovm"

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: tcovm.dev
vagrant_machine_name: tcovm
vagrant_ip: 192.168.88.89

# TCO-TOOL is a Drupal 7 distribution, not Drupal 8.
drupal_major_version: 7
drupal_install_profile: tco

# TCO-TOOL requires a new database name.
drupal_db_name: tco-tool

# Without extra modules.
drupal_enable_modules: ["tco_prefill_parameters"]

# Install drush extensions.
drush_enable_extensions: [ "registry_rebuild" ]

installed_extras:
  - drush
  - java
  # - memcached
  - solr
  # - varnish
  - xdebug

# Added extra packages needed to get the window manager up and running.
# And php5.6-zip to get ZipArchive required by
# PHPUnit_Extensions_Selenium2TestCase_SessionCommand_File.
extra_packages:
  - fluxbox
  - php5.6-zip
  - rungetty
  - sqlite
  - unzip
  - xorg

#use the virtual box GUI:
virtualbox_gui: true

# We use php 5.6 because this site will be hosted on the same server as a paddle website.
php_version: "5.6"

# The PHP INTL extension is required for the Drupal Culturefeed module.
php_packages_extra:
  - php5.6-intl

# Paddle gets 256M on the kañooh production servers.
php_memory_limit: "256M"

# Connect to the IDE on host machine to accept the debugging session.
php_xdebug_remote_host: 10.0.2.2
# Prevent "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" by
# increasing these settings to a value used on the kañooh production servers.
mysql_max_allowed_packet: 128M

