---
# This file overrides settings from default.config.yml to match the
# Meesterlijk Gezond server environment as good as possible for an optimal
# developer experience.
# Developer machine specific settings, such as path mappings, can be put in
# local.config.yml. See example.local.config.yml for an example local config
# YML file.
# See http://docs.drupalvm.com/en/latest/other/overriding-configurations/ for
# more information.
# Note: The merge of the variables in this file is shallow, so if you want to
# override a single item in a list, you will need to re-define all items in
# that list.

# Don't use composer to build a local Meesterlijk Gezond website.
drupal_build_composer_project: false
# Don't install Drupal at 'vagrant up'.
drupal_install_site: false

# Our Drupal code resides in the main synced directory, not in a 'drupal/web'
# sub folder.
drupal_core_path: "/var/www/meesterlijk-gezond"

# MEESTERLIJK GEZOND is a Drupal 7 distribution, not Drupal 8.
drupal_major_version: 7
drupal_install_profile: meesterlijk_gezond

# MEESTERLIJK GEZOND requires a new database name.
drupal_db_name: meesterlijk_gezond

# Install drush extensions.
drush_enable_extensions: [ "registry_rebuild" ]

installed_extras:
  - drush
  # - memcached
  - solr
  - xdebug
  - mailhog

# Cap the host CPU execution at 100% usage.
vagrant_cpuexecutioncap: 100
vagrant_videomemory: 16

# The PHP INTL extension is required.
php_packages_extra:
  - php7.1-intl

# Paddle projects receive 256M on the production servers.
php_memory_limit: "256M"

# Prevent "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" by
# increasing these settings to a value used on the production servers.
mysql_max_allowed_packet: 128M

# Don't only require vbguest and hostsupdater.
vagrant_plugins:
  - name: vagrant-auto_network
  - name: vagrant-hostmanager
  - name: vagrant-hostsupdater
  - name: vagrant-list
  - name: vagrant-reload
  - name: vagrant-vbguest
