---
# This file overrides settings from default.config.yml to match the Paddle
# server environment as good as possible for an optimal developer experience.
# Developer machine specific settings, such as path mappings, can be put in
# local.config.yml. See example.local.config.yml for an example local config
# YML file.
# See http://docs.drupalvm.com/en/latest/other/overriding-configurations/ for
# more information.
# Note: The merge of the variables in this file is shallow, so if you want to
# override a single item in a list, you will need to re-define all items in
# that list.
# Available `vagrant_box` values include:
#   - beet/box (pre-provisioned, based on Ubuntu 16.04)
#   - geerlingguy/centos7
#   - geerlingguy/centos6
#   - geerlingguy/debian9
#   - geerlingguy/debian8
#   - geerlingguy/ubuntu1604
#   - geerlingguy/ubuntu1404
vagrant_box: geerlingguy/ubuntu1604

# Don't use composer to build a local Paddle8 website, we will run it manually.
drupal_build_composer_project: false
# Don't install Drupal at 'vagrant up'.
drupal_install_site: false

# Our Drupal code resides in the main synced directory, not in a 'drupal/web'
# sub folder.
drupal_core_path: "/var/www/drupal8vm"

# Our vagrant host name should not conflict with the existing Paddle environment.
vagrant_hostname: drupal8vm.test
vagrant_machine_name: drupal8vm
vagrant_ip: 192.168.88.90

# Paddle 2.0 is a Drupal 8 distribution.
drupal_major_version: 8


# drush is installed per project. so we won't create the aliases here
configure_drush_aliases: false

## Install drush extensions.
#drush_enable_extensions: [ "registry_rebuild" ]

# Add Drush aliases for Paddle client websites.
# drush_aliases_guest_template: "templates/drupalvm-local-paddle.aliases.drushrc.php.j2"

installed_extras:
  # - memcached
  - nodejs
  - selenium
  - solr
  # - varnish
  - xdebug
  - mailhog

# Added extra packages needed to get the window manager up and running.
# And php7.1-zip to get ZipArchive required by
# PHPUnit_Extensions_Selenium2TestCase_SessionCommand_File.
extra_packages:
  - fluxbox
  - php7.1-zip
  - rungetty
  - sqlite
  - unzip
  - xorg

#use the virtual box GUI:
vagrant_gui: true

# Cap the host CPU execution at 100% usage.
vagrant_cpuexecutioncap: 100
vagrant_videomemory: 16

# The PHP INTL extension is required for the Drupal Culturefeed module.
php_packages_extra:
  - php7.1-intl

# Paddle gets 256M on the kañooh production servers.
php_memory_limit: "256M"

# Allow to run Selenium tests with Firefox inside the VM.
# Don't use
#selenium_install_firefox: yes
# from https://github.com/arknoll/ansible-role-selenium because it will always
# install the latest version of Firefox.
# Use https://github.com/arknoll/ansible-role-firefox/ instead and specify
# Firefox version 40 instead of the default 38.
firefox_version: '40.0'

# Prevent "SQLSTATE[HY000]: General error: 2006 MySQL server has gone away" by
# increasing these settings to a value used on the kañooh production servers.
mysql_max_allowed_packet: 128M

# Don't only require vbguest and hostsupdater.
vagrant_plugins:
  - name: vagrant-auto_network
  - name: vagrant-hostmanager
  - name: vagrant-hostsupdater
  - name: vagrant-list
  - name: vagrant-reload
  - name: vagrant-vbguest
